name: check testcode before PR
on:
  pull_request:
    types: [opened, reopened, synchronize]  
    paths:
      - "backend/src/main/**"
      - "backend/src/test/**"
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # PR 올린 레포지토리로 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # JDK 설치
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Gradle 캐시
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      # PR의 모든 commit 메시지가 'test:'를 포함하고 있는 지 검사
      - name: Check if all commit messages contain 'test:'
        id: skip-check
        uses: actions/github-script@v7
        with:
          script: |
            const commits = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            const allContainTest = commits.data.every(c => c.commit.message.includes('test:'));
            core.setOutput('skip', allContainTest ? 'true' : 'false');
            console.log(`All commits contain 'test': ${allContainTest}`);
            
      # 모든 커밋이 'test:'일 때 exit 0로 종료 (성공 처리)
      - name: Skip tests but mark as success
        if: steps.skip-check.outputs.skip == 'true'
        run: echo "✨ All commits contain 'test'. Marking workflow as SUCCESS without running tests."
          
      # 실행 권한 부여
      - name: Grant execute permission for gradlew
        if: steps.skip-check.outputs.skip == 'false'
        working-directory: ./backend
        run: chmod +x gradlew

      # 도커 정상 동작 여부 확인
      - name: Check Docker
        run: docker info

      # 테스트 실행
      - name: Run tests
        if: steps.skip-check.outputs.skip == 'false'
        working-directory: ./backend
        env:
          # testcontainers 실행시 발생할 수 있는 메모리 부족 방지를 위해 최대 힙메모리 지정
          GRADLE_OPTS: "-Xmx1024m"
        run: ./gradlew clean test
